### ISSUE TITLE
Code Issue #1

### ISSUE THREAD

**Issue by nakulnandhakumar** [kathyychenn/markdown-parse#1]
[Lines 34 - 37](https://github.com/kathyychenn/markdown-parse/blob/main/MarkdownParse.java#L34-L37)
<br>
The code sets currentIndex to closedParen + 1 on line 35, therefore, if there were just brackets enclosing text 
followed by an actual link `[<text>](<link>)` then the code would miss the link because it would set the currentIndex to after that closed parentheses before restarting the loop and finding the next open bracket.

Failed Test File: 
```
There are some words [with brackets] only and then [a](link).
```

**Comment by jackthomas00** [comment]
Error for Code Issue 1
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.base/java.lang.String.charAt(String.java:1512)
        at MarkdownParse.getLinks(MarkdownParse.java:24)
        at MarkdownParse.main(MarkdownParse.java:50)
