### ISSUE TITLE
Code Issue #2

### ISSUE THREAD

**Issue by nakulnandhakumar** [kathyychenn/markdown-parse#2]
[Lines 29 - 31](https://github.com/kathyychenn/markdown-parse/blob/main/MarkdownParse.java#L29-L31)
<br>

The code in MarkdownParse.java doesn’t consider if text exists after the last link. The code only makes sure there isn’t missing open parentheses and it should check for missing open/closed brackets and parentheses.

Failed Test File:
```
#Title

[a link!](https://something.com)
[another link!](some-page.html)

Some other sentence that will break the code.
```

**Comment by jackthomas00** [comment]
Error for Code Issue 2
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
at java.base/java.lang.String.charAt(String.java:1512)
at MarkdownParse.getLinks(MarkdownParse.java:24)
at MarkdownParse.main(MarkdownParse.java:50)
